CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public.keys (kid UUID UNIQUE PRIMARY KEY, key BYTEA);
CREATE TABLE IF NOT EXISTS public.user_agents (kid UUID UNIQUE PRIMARY KEY, user_agent TEXT);
CREATE TABLE IF NOT EXISTS public.token_ips (kid UUID, uid UUID, ip INET, port SMALLINT);